version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    environment:
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASSWORD=12345678
      - PG_HOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: {}
